name: Expense Project Extented
on:
  push:
    branches: 
     - temp
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 14
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build --prefix client


   
