name: Expense Project Extented
on:
  push:
    branches: 
     - temp
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read|write
      checks: read|write
      contents: read|write
      deployments: read|write
      id-token: read|write
      issues: read|write
      discussions: read|write
      packages: read|write
      pages: read|write
      pull-requests: read|write
      repository-projects: read|write
      security-events: read|write
      statuses: read|write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 14
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build --prefix client


   
